name: Validate OpenAPI

on:
  pull_request:
    paths:
      - 'openapi.yaml'
      - 'docs/**'

jobs:
  validate-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install openapi-cli
        run: |
          npm install -g @redocly/openapi-cli
      - name: Validate OpenAPI file
        run: |
          openapi lint openapi.yaml
